### ISSUE TITLE
Latest update breaks Node Loading

### ISSUE THREAD

**Issue by Piscabo** [lilly1987/ComfyUI_node_Lilly#10]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 0-57: character maps to <undefined>
*** You may need to add PYTHONIOENCODING=utf-8 to your environment ***

Cannot import A:\AI_Files\ComfyUI\custom_nodes\ComfyUI_node_Lilly module for custom nodes: 'charmap' codec can't encode characters in position 0-57: character maps to <undefined>
*** You may need to add PYTHONIOENCODING=utf-8 to your environment ***
![image](https://github.com/lilly1987/ComfyUI_node_Lilly/assets/123719842/c9ae5211-9144-4def-90cc-12e55b658274)

I did try to set the environment, also not working. "set PYTHONUTF8=1"

**Comment by Piscabo** [comment]
![image](https://github.com/lilly1987/ComfyUI_node_Lilly/assets/123719842/dc13aa2f-8c9a-49d3-b42c-718b338bccef)

**Is anyone looking at this?**

__name__ : ComfyUI_node_Lilly
__file__ : A:\AI_Files\ComfyUI\custom_nodes\ComfyUI_node_Lilly\__init__.py
os.path.basename(__file__) : __init__.py
os.path.splitext(os.path.basename(__file__))[0] : __init__
working directory :  A:\AI_Files\ComfyUI
Traceback (most recent call last):
  File "A:\AI_Files\ComfyUI\nodes.py", line 1647, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "A:\AI_Files\ComfyUI\custom_nodes\ComfyUI_node_Lilly\__init__.py", line 87, in <module>
    console.rule(f" init start ", style="bold green")
  File "A:\AI_Files\stable-diffusion-webui\venv\lib\site-packages\rich\console.py", line 1579, in rule
    self.print(rule)
  File "A:\AI_Files\stable-diffusion-webui\venv\lib\site-packages\rich\console.py", line 1672, in print
    with self:
  File "A:\AI_Files\stable-diffusion-webui\venv\lib\site-packages\rich\console.py", line 864, in __exit__
    self._exit_buffer()
  File "A:\AI_Files\stable-diffusion-webui\venv\lib\site-packages\rich\console.py", line 822, in _exit_buffer
    self._check_buffer()
  File "A:\AI_Files\stable-diffusion-webui\venv\lib\site-packages\rich\console.py", line 2038, in _check_buffer
    write(text)
  File "A:\AI_Files\ComfyUI\custom_nodes\ComfyUI-Manager\prestartup_script.py", line 22, in write
    self.file.write(message)
  File "C:\Program Files\Python310\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 0-57: character maps to <undefined>
*** You may need to add PYTHONIOENCODING=utf-8 to your environment ***

Cannot import A:\AI_Files\ComfyUI\custom_nodes\ComfyUI_node_Lilly module for custom nodes: 'charmap' codec can't encode characters in position 0-57: character maps to <undefined>
*** You may need to add PYTHONIOENCODING=utf-8 to your environment ***
Using pytorch cross attention

**Comment by Ferniclestix** [comment]
I bypassed this glitch and node won't work correctly so imma uninstall.

**Comment by Piscabo** [comment]
Yeah me too... NO support. Was trying to make use of it but this is too frustrating!

**Comment by lilly1987** [comment]
ComfyUI에게 물어봐야 할 것 같습니다.
아마도 그것을 해결하는 방법.
재현할 방법을 몰라서 검증이 안됨.

I guess I'll have to ask ComfyUI.
maybe a way to solve it.
I can't verify it because I don't know how to reproduce it.

```
ComfyUI_windows_portable\run_nvidia_gpu.bat edit
first line input 'chcp 65001'
```
![2023-08-18 10 14 22](https://github.com/lilly1987/ComfyUI_node_Lilly/assets/20321215/cc03c429-95b4-470e-9e40-fd655ba31600)
